/* HeaderBar.c generated by valac 0.56.13, the Vala compiler
 * generated from HeaderBar.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define MY_APP_TYPE_HEADER_BAR (my_app_header_bar_get_type ())
#define MY_APP_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_APP_TYPE_HEADER_BAR, MyAppHeaderBar))
#define MY_APP_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_APP_TYPE_HEADER_BAR, MyAppHeaderBarClass))
#define MY_APP_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_APP_TYPE_HEADER_BAR))
#define MY_APP_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_APP_TYPE_HEADER_BAR))
#define MY_APP_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_APP_TYPE_HEADER_BAR, MyAppHeaderBarClass))

typedef struct _MyAppHeaderBar MyAppHeaderBar;
typedef struct _MyAppHeaderBarClass MyAppHeaderBarClass;
typedef struct _MyAppHeaderBarPrivate MyAppHeaderBarPrivate;
enum  {
	MY_APP_HEADER_BAR_0_PROPERTY,
	MY_APP_HEADER_BAR_WINDOW_STACK_PROPERTY,
	MY_APP_HEADER_BAR_NUM_PROPERTIES
};
static GParamSpec* my_app_header_bar_properties[MY_APP_HEADER_BAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MyAppHeaderBar {
	GtkHeaderBar parent_instance;
	MyAppHeaderBarPrivate * priv;
};

struct _MyAppHeaderBarClass {
	GtkHeaderBarClass parent_class;
};

struct _MyAppHeaderBarPrivate {
	GtkStack* _window_stack;
};

static gint MyAppHeaderBar_private_offset;
static gpointer my_app_header_bar_parent_class = NULL;

VALA_EXTERN GType my_app_header_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyAppHeaderBar, g_object_unref)
VALA_EXTERN MyAppHeaderBar* my_app_header_bar_new (GtkStack* stack);
VALA_EXTERN MyAppHeaderBar* my_app_header_bar_construct (GType object_type,
                                             GtkStack* stack);
VALA_EXTERN GtkStack* my_app_header_bar_get_window_stack (MyAppHeaderBar* self);
static void my_app_header_bar_set_window_stack (MyAppHeaderBar* self,
                                         GtkStack* value);
static GObject * my_app_header_bar_constructor (GType type,
                                         guint n_construct_properties,
                                         GObjectConstructParam * construct_properties);
static void my_app_header_bar_finalize (GObject * obj);
static GType my_app_header_bar_get_type_once (void);
static void _vala_my_app_header_bar_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec);
static void _vala_my_app_header_bar_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec);

static inline gpointer
my_app_header_bar_get_instance_private (MyAppHeaderBar* self)
{
	return G_STRUCT_MEMBER_P (self, MyAppHeaderBar_private_offset);
}

MyAppHeaderBar*
my_app_header_bar_construct (GType object_type,
                             GtkStack* stack)
{
	MyAppHeaderBar * self = NULL;
	g_return_val_if_fail (stack != NULL, NULL);
	self = (MyAppHeaderBar*) g_object_new (object_type, "window-stack", stack, NULL);
	return self;
}

MyAppHeaderBar*
my_app_header_bar_new (GtkStack* stack)
{
	return my_app_header_bar_construct (MY_APP_TYPE_HEADER_BAR, stack);
}

GtkStack*
my_app_header_bar_get_window_stack (MyAppHeaderBar* self)
{
	GtkStack* result;
	GtkStack* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_window_stack;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
my_app_header_bar_set_window_stack (MyAppHeaderBar* self,
                                    GtkStack* value)
{
	GtkStack* old_value;
	g_return_if_fail (self != NULL);
	old_value = my_app_header_bar_get_window_stack (self);
	if (old_value != value) {
		GtkStack* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_window_stack);
		self->priv->_window_stack = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, my_app_header_bar_properties[MY_APP_HEADER_BAR_WINDOW_STACK_PROPERTY]);
	}
}

static GObject *
my_app_header_bar_constructor (GType type,
                               guint n_construct_properties,
                               GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MyAppHeaderBar * self;
	GtkStackSwitcher* stack_switcher = NULL;
	GtkStackSwitcher* _tmp0_;
	GtkStackSwitcher* _tmp1_;
	GtkStack* _tmp2_;
	GtkStackSwitcher* _tmp3_;
	parent_class = G_OBJECT_CLASS (my_app_header_bar_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MY_APP_TYPE_HEADER_BAR, MyAppHeaderBar);
	gtk_header_bar_set_show_close_button ((GtkHeaderBar*) self, TRUE);
	_tmp0_ = (GtkStackSwitcher*) gtk_stack_switcher_new ();
	g_object_ref_sink (_tmp0_);
	stack_switcher = _tmp0_;
	_tmp1_ = stack_switcher;
	_tmp2_ = self->priv->_window_stack;
	gtk_stack_switcher_set_stack (_tmp1_, _tmp2_);
	_tmp3_ = stack_switcher;
	gtk_header_bar_set_custom_title ((GtkHeaderBar*) self, (GtkWidget*) _tmp3_);
	_g_object_unref0 (stack_switcher);
	return obj;
}

static void
my_app_header_bar_class_init (MyAppHeaderBarClass * klass,
                              gpointer klass_data)
{
	my_app_header_bar_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &MyAppHeaderBar_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_my_app_header_bar_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_my_app_header_bar_set_property;
	G_OBJECT_CLASS (klass)->constructor = my_app_header_bar_constructor;
	G_OBJECT_CLASS (klass)->finalize = my_app_header_bar_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MY_APP_HEADER_BAR_WINDOW_STACK_PROPERTY, my_app_header_bar_properties[MY_APP_HEADER_BAR_WINDOW_STACK_PROPERTY] = g_param_spec_object ("window-stack", "window-stack", "window-stack", gtk_stack_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}

static void
my_app_header_bar_instance_init (MyAppHeaderBar * self,
                                 gpointer klass)
{
	self->priv = my_app_header_bar_get_instance_private (self);
}

static void
my_app_header_bar_finalize (GObject * obj)
{
	MyAppHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MY_APP_TYPE_HEADER_BAR, MyAppHeaderBar);
	_g_object_unref0 (self->priv->_window_stack);
	G_OBJECT_CLASS (my_app_header_bar_parent_class)->finalize (obj);
}

static GType
my_app_header_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MyAppHeaderBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_app_header_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyAppHeaderBar), 0, (GInstanceInitFunc) my_app_header_bar_instance_init, NULL };
	GType my_app_header_bar_type_id;
	my_app_header_bar_type_id = g_type_register_static (gtk_header_bar_get_type (), "MyAppHeaderBar", &g_define_type_info, 0);
	MyAppHeaderBar_private_offset = g_type_add_instance_private (my_app_header_bar_type_id, sizeof (MyAppHeaderBarPrivate));
	return my_app_header_bar_type_id;
}

GType
my_app_header_bar_get_type (void)
{
	static volatile gsize my_app_header_bar_type_id__once = 0;
	if (g_once_init_enter (&my_app_header_bar_type_id__once)) {
		GType my_app_header_bar_type_id;
		my_app_header_bar_type_id = my_app_header_bar_get_type_once ();
		g_once_init_leave (&my_app_header_bar_type_id__once, my_app_header_bar_type_id);
	}
	return my_app_header_bar_type_id__once;
}

static void
_vala_my_app_header_bar_get_property (GObject * object,
                                      guint property_id,
                                      GValue * value,
                                      GParamSpec * pspec)
{
	MyAppHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MY_APP_TYPE_HEADER_BAR, MyAppHeaderBar);
	switch (property_id) {
		case MY_APP_HEADER_BAR_WINDOW_STACK_PROPERTY:
		g_value_set_object (value, my_app_header_bar_get_window_stack (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_my_app_header_bar_set_property (GObject * object,
                                      guint property_id,
                                      const GValue * value,
                                      GParamSpec * pspec)
{
	MyAppHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MY_APP_TYPE_HEADER_BAR, MyAppHeaderBar);
	switch (property_id) {
		case MY_APP_HEADER_BAR_WINDOW_STACK_PROPERTY:
		my_app_header_bar_set_window_stack (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

