/* Main.c generated by valac 0.56.13, the Vala compiler
 * generated from Main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_NOSTALGIA (nostalgia_get_type ())
#define NOSTALGIA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NOSTALGIA, Nostalgia))
#define NOSTALGIA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NOSTALGIA, NostalgiaClass))
#define IS_NOSTALGIA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NOSTALGIA))
#define IS_NOSTALGIA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NOSTALGIA))
#define NOSTALGIA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NOSTALGIA, NostalgiaClass))

typedef struct _Nostalgia Nostalgia;
typedef struct _NostalgiaClass NostalgiaClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static gint _vala_main (gchar** args,
                 gint args_length1);
VALA_EXTERN GType nostalgia_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Nostalgia, g_object_unref)
VALA_EXTERN Nostalgia* nostalgia_new (void);
VALA_EXTERN Nostalgia* nostalgia_construct (GType object_type);

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	Nostalgia* nostalgia = NULL;
	Nostalgia* _tmp0_;
	gint result;
	_tmp0_ = nostalgia_new ();
	nostalgia = _tmp0_;
	result = g_application_run ((GApplication*) nostalgia, (gint) args_length1, args);
	_g_object_unref0 (nostalgia);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

