/* Nostalgia.c generated by valac 0.56.13, the Vala compiler
 * generated from Nostalgia.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_NOSTALGIA (nostalgia_get_type ())
#define NOSTALGIA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NOSTALGIA, Nostalgia))
#define NOSTALGIA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NOSTALGIA, NostalgiaClass))
#define IS_NOSTALGIA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NOSTALGIA))
#define IS_NOSTALGIA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NOSTALGIA))
#define NOSTALGIA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NOSTALGIA, NostalgiaClass))

typedef struct _Nostalgia Nostalgia;
typedef struct _NostalgiaClass NostalgiaClass;
typedef struct _NostalgiaPrivate NostalgiaPrivate;
enum  {
	NOSTALGIA_0_PROPERTY,
	NOSTALGIA_NUM_PROPERTIES
};
static GParamSpec* nostalgia_properties[NOSTALGIA_NUM_PROPERTIES];

#define MY_APP_TYPE_WINDOW (my_app_window_get_type ())
#define MY_APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MY_APP_TYPE_WINDOW, MyAppWindow))
#define MY_APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MY_APP_TYPE_WINDOW, MyAppWindowClass))
#define MY_APP_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MY_APP_TYPE_WINDOW))
#define MY_APP_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MY_APP_TYPE_WINDOW))
#define MY_APP_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MY_APP_TYPE_WINDOW, MyAppWindowClass))

typedef struct _MyAppWindow MyAppWindow;
typedef struct _MyAppWindowClass MyAppWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Nostalgia {
	GtkApplication parent_instance;
	NostalgiaPrivate * priv;
};

struct _NostalgiaClass {
	GtkApplicationClass parent_class;
};

static gpointer nostalgia_parent_class = NULL;

VALA_EXTERN GType nostalgia_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Nostalgia, g_object_unref)
VALA_EXTERN Nostalgia* nostalgia_new (void);
VALA_EXTERN Nostalgia* nostalgia_construct (GType object_type);
static void nostalgia_real_activate (GApplication* base);
VALA_EXTERN GType my_app_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyAppWindow, g_object_unref)
VALA_EXTERN MyAppWindow* my_app_window_new (Nostalgia* application);
VALA_EXTERN MyAppWindow* my_app_window_construct (GType object_type,
                                      Nostalgia* application);
static GType nostalgia_get_type_once (void);

Nostalgia*
nostalgia_construct (GType object_type)
{
	Nostalgia * self = NULL;
	self = (Nostalgia*) g_object_new (object_type, "application-id", "com.github.konickss.nostalgia", "flags", G_APPLICATION_FLAGS_NONE, NULL);
	return self;
}

Nostalgia*
nostalgia_new (void)
{
	return nostalgia_construct (TYPE_NOSTALGIA);
}

static void
nostalgia_real_activate (GApplication* base)
{
	Nostalgia * self;
	MyAppWindow* window = NULL;
	MyAppWindow* _tmp0_;
	self = (Nostalgia*) base;
	_tmp0_ = my_app_window_new (self);
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) window);
	_g_object_unref0 (window);
}

static void
nostalgia_class_init (NostalgiaClass * klass,
                      gpointer klass_data)
{
	nostalgia_parent_class = g_type_class_peek_parent (klass);
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) nostalgia_real_activate;
}

static void
nostalgia_instance_init (Nostalgia * self,
                         gpointer klass)
{
}

static GType
nostalgia_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NostalgiaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) nostalgia_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Nostalgia), 0, (GInstanceInitFunc) nostalgia_instance_init, NULL };
	GType nostalgia_type_id;
	nostalgia_type_id = g_type_register_static (gtk_application_get_type (), "Nostalgia", &g_define_type_info, 0);
	return nostalgia_type_id;
}

GType
nostalgia_get_type (void)
{
	static volatile gsize nostalgia_type_id__once = 0;
	if (g_once_init_enter (&nostalgia_type_id__once)) {
		GType nostalgia_type_id;
		nostalgia_type_id = nostalgia_get_type_once ();
		g_once_init_leave (&nostalgia_type_id__once, nostalgia_type_id);
	}
	return nostalgia_type_id__once;
}

